beehive/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views
from django.conf import settings
from django.conf.urls.static import static
from user_management.views import ApprovalListView
from dashboard.views import NoticeBoardListView

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('', include('dashboard.urls')),
    path('approvals/', ApprovalListView.as_view(), name='approvals'),
    path('notice-board/', NoticeBoardListView.as_view(), name='notice_board'),
    path('cimplux-admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('employee/', include('employees.urls')),
    path('user-management/', include('user_management.urls')),
    path('self-service/', include('self_panel.urls', namespace='self_panel')),
    path('admin/', include('accounts.urls_admin')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

leave/urls.py
from django.urls import path
from .views import *

app_name = 'leave'

master_leave_patterns = [
    path('master/creation/', LeaveMasterListView.as_view(), name='leave_master_list'),
    path('master/creation/create/', LeaveMasterCreateView.as_view(), name='leave_master_create'),
    path('master/creation/<pk>/update/', LeaveMasterUpdateView.as_view(), name='leave_master_edit'),
    path('master/creation/<pk>/delete/', LeaveDeleteView.as_view(), name='leave_master_delete'),
]

master_leave_group_patterns = [
    path('master/group/', LeaveGroupListView.as_view(), name='leave_group_list'),
    path('master/group/create/', LeaveGroupCreateView.as_view(), name='leave_group_create'),
    path('master/group/<pk>/update/', LeaveGroupUpdateView.as_view(), name='leave_group_edit'),
    path('master/group/<pk>/delete/', LeaveGroupDeleteView.as_view(), name='leave_group_delete'),
]

process_leave_patterns = [
    path('process/entry/', LeaveEntryListView.as_view(), name='leave_entry_list'),
    path('process/entry/new/', LeaveEntryCreateView.as_view(), name='leave_entry_new'),
    path('process/entry/new/<pk>/edit/?query=<employee_id>', LeaveEntryCreateView.as_view(), name='leave_entry_new_edit'),
    path('process/entry/<pk>/details/?query=<employee_id>', LeaveEntryDetailsView.as_view(), name='leave_entry_details'),
    path('process/entry/list/?query=<pk>', LeaveIndividualListView.as_view(), name='leave_entry_individual_list'),
    path('process/entry/new/leave_entry_search/', LeaveEntrySearchView.as_view(), name='leave_entry_search'),
    path('process/entry/leave_entry_search/', LeaveEntrySearchView.as_view(), name='entry_search_employee'),
    path('process/leave_approval/list/', LeavePendingListView.as_view(), name='leave_approval_list'),
    path('process/leave_approval/<pk>/', LeaveApprovalView.as_view(), name='leave_approval_form'),
    path('process/leave_approval/list/leave_entry_search/', LeaveEntrySearchView.as_view(), name='leave_entry_search'),
]

leave_report_patterns = [
    path('report/', LeaveReportView.as_view(), name='leave_report'),
    path('report/leave_entry_search/', LeaveEntrySearchView.as_view(), name='leave_entry_search'),
]

urlpatterns = master_leave_patterns + master_leave_group_patterns + process_leave_patterns + leave_report_patterns

user_management/urls.py
from django.urls import path
from .views import (
    RoleCreationListView, RoleCreationCreateView, RoleCreationUpdateView, RoleCreationDeleteView,
    UserCreationListView, UserCreationCreateView, UserCreationUpdateView, UserCreationDeleteView, ResetPasswordView,
    RoleHierarchyListView, RoleHierarchyCreateView, RoleHierarchyUpdateView, RoleHierarchyDeleteView,
    WorkflowListView, WorkflowCreateView, WorkflowUpdateView, WorkflowDeleteView,
)

app_name = 'user_management'

urlpatterns = [
    path('roles/', RoleCreationListView.as_view(), name='roles_list'),
    path('roles/create/', RoleCreationCreateView.as_view(), name='roles_create'),
    path('roles/<pk>/update/', RoleCreationUpdateView.as_view(), name='roles_update'),
    path('roles/<pk>/delete/', RoleCreationDeleteView.as_view(), name='roles_delete'),

    # User creation
    path('users/', UserCreationListView.as_view(), name='users_list'),
    path('users/create/', UserCreationCreateView.as_view(), name='users_create'),
    path('users/<pk>/update/', UserCreationUpdateView.as_view(), name='users_update'),
    path('users/<pk>/password-reset/', ResetPasswordView.as_view(), name='users_password_reset'),
    path('users/<pk>/delete/', UserCreationDeleteView.as_view(), name='users_delete'),

    # Role hierarchy
    path('role_hierarchies/', RoleHierarchyListView.as_view(), name='role_hierarchies_list'),
    path('role_hierarchies/create/', RoleHierarchyCreateView.as_view(), name='role_hierarchies_create'),
    path('role_hierarchies/<pk>/update/', RoleHierarchyUpdateView.as_view(), name='role_hierarchies_update'),
    path('role_hierarchies/<pk>/delete/', RoleHierarchyDeleteView.as_view(), name='role_hierarchies_delete'),

    # Workflow
    path('workflows/', WorkflowListView.as_view(), name='workflows_list'),
    path('workflows/<id>/define/', WorkflowCreateView.as_view(), name='workflows_create'),
    path('workflows/<content_id>/update/<pk>/', WorkflowUpdateView.as_view(), name='workflows_update'),
    path('workflows/<content_id>/delete/<pk>/', WorkflowDeleteView.as_view(), name='workflows_delete'),
]

user_management/models.py
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.contrib.auth.models import (
    AbstractBaseUser, BaseUserManager, PermissionsMixin, Group
)

from employees.models import EmployeeIdentification
from helpers.models import Model
from setting.models import Branch, Company


class UserManager(BaseUserManager):
    def create_user(self, email, name=None, password=None, is_staff=False,
                    is_management=False, is_superuser=False, is_active=True, user_type=None):
        if not email:
            raise ValueError('Users must have a email address')
        if not password:
            raise ValueError('Users must have a password')

        user_obj = self.model(
            email=self.normalize_email(email),
            name=name,
            management=is_management,
            is_staff=is_staff,
            is_superuser=is_superuser,
            user_type=user_type
        )
        user_obj.active = is_active
        user_obj.set_password(password)
        user_obj.save(using=self._db)

        return user_obj

    def create_staffuser(self, email, name=None, password=None):
        user = self.create_user(
            email,
            name=name,
            password=password,
            is_staff=True
        )
        return user

    def create_superuser(self, email, name=None, password=None):
        user = self.create_user(
            email,
            name=name,
            password=password,
            is_staff=True,
            is_management=True,
            is_superuser=True,
            user_type='system-user'
        )

        return user


class User(AbstractBaseUser, PermissionsMixin):
    USER_TYPE_CHOICES = (
        ('employee-user', 'Employee User'),
        ('system-user', 'System User')
    )
    DASHBOARD_CHOICES = (
        ('employee', 'Employee'),
        ('management', 'Management'),
        ('admin', 'Admin'),
    )

    name = models.CharField(max_length=255, blank=True, null=True)
    date_of_birth = models.DateField(blank=True, null=True)
    phone = models.CharField(max_length=255, blank=True, null=True)
    email = models.EmailField(max_length=255, unique=True)
    user_type = models.CharField(max_length=15, choices=USER_TYPE_CHOICES)
    employee = models.OneToOneField(EmployeeIdentification, on_delete=models.CASCADE, blank=True, null=True)
    management = models.BooleanField(default=False, blank=True)
    dashboard = models.CharField(max_length=10, null=True, choices=DASHBOARD_CHOICES)
    groups = models.ManyToManyField(
        Group,
        blank=True,
        through='UserGroup'
    )
    is_staff = models.BooleanField(default=False, blank=True)
    status = models.CharField(max_length=10, blank=True, choices=(
        ('active', 'Active'),
        ('inactive', 'Inactive')
    ), default='active')
    self_panel = models.BooleanField(default=False, blank=True)
    created_at = models.DateTimeField(blank=True, auto_now_add=True)
    updated_at = models.DateTimeField(blank=True, auto_now=True)

    USERNAME_FIELD = 'email'

    objects = UserManager()

    def __str__(self):
        if self.user_type == 'employee-user':
            return '%s' % self.employee

        return "%s" % self.name


class UserGroup(Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)

    def __str__(self):
        return self.group.name


class RoleHierarchy(Model):
    parent_role = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True)
    level = models.PositiveIntegerField()
    role = models.ForeignKey(Group, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.level)


class Workflow(Model):
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    status = models.CharField(max_length=10, choices=(
        ('undefined', 'Undefined'),
        ('defined', 'Defined')
    ), blank=True, default='undefined')


class WorkflowVariation(Model):
    workflow = models.ForeignKey(Workflow, on_delete=models.CASCADE)


class WorkflowVariationInitiator(Model):
    workflow_variation = models.ForeignKey(WorkflowVariation, on_delete=models.CASCADE)
    initiator = models.ForeignKey(Group, on_delete=models.CASCADE)


class WorkflowVariationLevel(Model):
    workflow_variation = models.ForeignKey(WorkflowVariation, on_delete=models.CASCADE)
    level = models.PositiveIntegerField()


class WorkflowApproval(Model):
    workflow_variation_level = models.ForeignKey(WorkflowVariationLevel, on_delete=models.CASCADE)
    approved_by = models.ForeignKey(Group, on_delete=models.CASCADE)
    next_approval_operator = models.CharField(max_length=3, choices=(
        ('and', 'And'),
        ('or', 'Or')
    ), blank=True, null=True)


class WorkflowNotificationRecipient(Model):
    workflow_variation_level = models.ForeignKey(WorkflowVariationLevel, on_delete=models.CASCADE)
    notification_recipient = models.ManyToManyField(Group, blank=False)


Group.add_to_class('code', models.CharField(max_length=255, blank=True, null=True))
Group.add_to_class('description', models.TextField(blank=True, null=True))
Group.add_to_class('status', models.CharField(max_length=10, blank=True, choices=(
    ('active', 'Active'),
    ('inactive', 'Inactive')
), default='active'))
Group.add_to_class('created_at', models.DateTimeField(auto_now_add=True))
Group.add_to_class('updated_at', models.DateTimeField(auto_now=True))


class Approval(Model):
    TYPE_CHOICES = [
        ('late-entry', 'Late Entry'),
        ('early-out', 'Early Out'),
        ('leave', 'Leave')
    ]
    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('approved', 'Approved'),
        ('declined', 'Declined')
    ]

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    item = models.IntegerField()
    item_type = models.CharField(max_length=10, choices=TYPE_CHOICES, blank=True)
    content_object = GenericForeignKey('content_type', 'item')
    reporting = models.ForeignKey(EmployeeIdentification, on_delete=models.CASCADE)
    operator = models.CharField(max_length=3, blank=True, null=True)
    level = models.IntegerField(null=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, blank=True, default='pending')


class ApprovalNotification(Model):
    content = models.TextField()
    to = models.ForeignKey(EmployeeIdentification, on_delete=models.CASCADE)

user_management/views.py
from django.shortcuts import render

# Create your views here.

user_management/views/approvals.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView, UpdateView

from helpers.mixins import PermissionMixin
from user_management.workflow import Approval
from dashboard.views import map_for_approval


class ApprovalListView(LoginRequiredMixin, PermissionMixin, TemplateView):
    template_name = 'user_management/approvals/list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        approvals = Approval(self.request).get()
        approvals = list(map(map_for_approval, approvals))

        context['permissions'] = self.get_current_user_permission_list()
        context['approvals_pending'] = list(
            filter(lambda approval: approval['status'] == 'pending', approvals)
        )
        context['approvals_approved'] = list(
            filter(lambda approval: approval['status'] == 'approved', approvals)
        )
        context['approvals_declined'] = list(
            filter(lambda approval: approval['status'] == 'declined', approvals)
        )

        return context

user_management/views/role_hierarchy.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from helpers.mixins import PermissionMixin
from user_management.models import RoleHierarchy
from helpers.functions import get_organizational_structure


class RoleHierarchyListView(ListView, PermissionMixin, LoginRequiredMixin):
    """List of role hierarchies."""

    template_name = 'user_management/role_hierarchy/list.html'
    model = RoleHierarchy
    context_object_name = 'role_hierarchies'
    permission_required = ['add_rolehierarchy', 'change_rolehierarchy', 'delete_rolehierarchy', 'view_rolehierarchy']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['permissions'] = self.get_current_user_permission_list()
        context['org_items_list'] = get_organizational_structure()
        return context


class RoleHierarchyCreateView(LoginRequiredMixin, PermissionMixin, CreateView):
    """Show the form to create and store the newly created hierarchy."""

    template_name = 'user_management/role_hierarchy/create.html'
    model = RoleHierarchy
    fields = '__all__'
    success_url = reverse_lazy('user_management:role_hierarchies_list')
    permission_required = 'add_rolehierarchy'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['permissions'] = self.get_current_user_permission_list()
        context['org_items_list'] = get_organizational_structure()
        return context


class RoleHierarchyUpdateView(LoginRequiredMixin, PermissionMixin, UpdateView):
    """Show the form to update the specified hierarchy."""

    template_name = 'user_management/role_hierarchy/update.html'
    model = RoleHierarchy
    fields = '__all__'
    success_url = reverse_lazy('user_management:role_hierarchies_list')
    permission_required = 'change_rolehierarchy'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['permissions'] = self.get_current_user_permission_list()
        context['org_items_list'] = get_organizational_structure()
        return context


class RoleHierarchyDeleteView(LoginRequiredMixin, PermissionMixin, DeleteView):
    """Delete the specified role."""

    template_name = 'user_management/role_hierarchy/delete.html'
    model = RoleHierarchy
    success_url = reverse_lazy('user_management:role_hierarchies_list')
    permission_required = 'delete_rolehierarchy'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['permissions'] = self.get_current_user_permission_list()
        context['org_items_list'] = get_organizational_structure()
        return context

user_management/templates/user_management/role_hierarchy/create.html
{% extends "layouts/master.html" %}

{% block title %}Add a new Level{% endblock %}

{% block content %}
<div class='container'>
    <div class='row justify-content-md-center'>
        <div class="col-md-12">
            <div class='card'>
                <div class="card-header secondary">
                    <h2>Create a new Level</h2>
                    <p>Text from Shimanto</p>
                </div>
                <div class="card-block">
                    <form method="post" novalidate>
                        {% csrf_token %}

                        <div>
                            {% include 'user_management/role_hierarchy/form.html' %}
                        </div>

                        <div class="form-group text-right">
                            <a class="btn btn-main  b-none" href="{% url 'user_management:role_hierarchies_list' %}">Cancel</a>
                            <button type="submit" class="btn btn-main">Create Level</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

user_management/templates/user_management/role_hierarchy/delete.html
{% extends "layouts/master.html" %}

{% block title %}Delete a role hierarchy{% endblock %}

{% block content %}
<div class='container'>
    <div class='row justify-content-md-center'>
        <div class="col-md-12">
            <div class='card'>
                <div class="card-header secondary">
                    <h2>Delete hierarchy</h2>
                    <p>Confirm delete hierarchy</p>
                </div>
                <div class="card-block">
                    <form method="post">
                        {% csrf_token %}

                        <p>Are you sure you want to delete "{{ object }}"?</p>
                        <input type="submit" value="Yes, I am sure" class='btn btn-main red'>
                        <a class="btn btn-main" href="{% url 'user_management:role_hierarchies_list' %}">No, take me back</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

user_management/templates/user_management/role_hierarchy/form.html
<div class="form-group row">
    <div class="col-md-6">
        <label for="{{ form.level.id_for_label }}">{{ form.level.label }}</label>
        <input type="number" name="{{ form.level.name }}" id="{{ form.level.id_for_label }}"
               class="w-100 form-control{% if form.level.errors %} is-invalid{% endif %}"
               value="{{ form.level.value|default_if_none:0 }}">

        {% if form.level.errors %}
            {% for error in form.level.errors %}
                <div class="invalid-feedback">{{ error }}</div>
            {% endfor %}
        {% endif %}
    </div>

    <div class="col-md-6">
        <label for="{{ form.role.id_for_label }}">{{ form.role.label }}</label>
        <select name="{{ form.role.name }}" id="{{ form.role.id_for_label }}"
                class="form-control{% if form.role.errors %} is-invalid{% endif %}">
            {% for option in form.role.field.choices %}
                <option value="{{ option.0 }}">{{ option.1 }}</option>
            {% endfor %}
        </select>

        {% if form.role.errors %}
            {% for error in form.role.errors %}
                <div class="invalid-feedback">{{ error }}</div>
            {% endfor %}
        {% endif %}
    </div>
</div>

user_management/templates/user_management/role_hierarchy/list.html
{% extends "layouts/master.html" %}

{% block title %}Role Hierarchy{% endblock %}

{% block content %}
{% include 'layouts/event.html' %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            {% if request.user.is_superuser or 'add_rolehierarchy' in permissions %}
            <div class="text-right">
                <a href="{% url 'user_management:role_hierarchies_create' %}" class="btn btn-main m-0">+
                    Add a new role
                </a>
            </div>
            {% endif %}

            <div class="card">
                <div class="card-header secondary card-box">
                    <div class="card-title">
                        <p>User Management</p>
                        <h2>Role Hierarchy</h2>
                    </div>
                </div>

                <div class="card-block">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="table-responsive">
                                <table class="table table-hover">
                                    <thead>
                                        <tr class="selectable">
                                            <th scope="col">Level</th>
                                            <th scope="col">Allocated Role</th>
                                            <th scope="col">Parent</th>
                                            <th scope="col">Status</th>
                                            <th scope="col">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for rh in role_hierarchies %}
                                            <tr>
                                                <td>{{ rh.level }}</td>
                                                <td>{{ rh.role }}</td>
                                                <td>{{ rh.parent_role }}</td>
                                                <td>{{ rh.get_status_display }}</td>
                                                <td>
                                                    {% if request.user.is_superuser or 'change_rolehierarchy' in permissions %}
                                                        <a title="edit" class="btn btn-outline-metal m-btn m-btn--icon m-btn--icon-only m-btn--outline" href="{% url 'user_management:role_hierarchies_update' rh.id %}">
                                                            <i class="la la-edit"></i>
                                                        </a>
                                                    {% endif %}

                                                    {% if request.user.is_superuser or 'delete_rolehierarchy' in permissions %}
                                                        <a title="delete" class="btn btn-outline-danger m-btn m-btn--icon m-btn--icon-only m-btn--outline" href="{% url 'user_management:role_hierarchies_delete' rh.id %}">
                                                            <i class="la la-times-circle-o"></i>
                                                        </a>
                                                    {% endif %}
                                                </td>
                                            </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

user_management/templates/user_management/role_hierarchy/update.html
{% extends "layouts/master.html" %}

{% block title %}Update Level{% endblock %}

{% block content %}
<div class='container'>
    <div class='row justify-content-md-center'>
        <div class="col-md-12">
            <div class='card'>
                <div class="card-header secondary">
                    <h2>Update Role</h2>
                    <p>Text from Shimanto</p>
                </div>
                <div class="card-block">
                    <form method="post" novalidate>
                        {% csrf_token %}

                        <div>
                            {% include 'user_management/role_hierarchy/form.html' %}
                        </div>

                        <div class="form-group text-right">
                            <a class="btn btn-main  b-none" href="{% url 'user_management:role_hierarchies_list' %}">Cancel</a>
                            <button type="submit" class="btn btn-main">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}